spring.application.name=Plateforme Mini d'apprentissage Etudiant

spring.datasource.url=jdbc:postgresql://localhost:5432/Plateforme_Etudiant
spring.datasource.username=postgres
spring.datasource.password=tsiririmlay

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecte PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Pour PostgreSQL 15+

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Pool de connexions (HikariCP)
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

security.basic.enabled=false
management.security.enabled=false

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**

spring.websocket.sockjs.client-library-url=https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js

spring.jmx.enabled=false
anagement.endpoints.jmx.exposure.exclude=*

# Upload file configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Dossier de stockage des fichiers uploadés
file.upload-dir=./uploads
file.upload-dir-absolute=D:/uploads

# URL d'accès aux fichiers
file.base-url=/uploads/

